### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by nahidakbar** [iocast/atom-esdoc#2]
[Enter steps to reproduce:]

Messes up git tab commit message input box

1. open up git tab
2. try entering a commit message that spans more than one line. as soon as you press enter, esdoc plugin will error out

why is esdoc trying to format my git commit message?

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [esdoc](https://github.com/iocast/atom-esdoc) package 0.0.7

### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /home/god/.atom/packages/esdoc/lib/esdoc.js:73

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at Object.parseEnter (/packages/esdoc/lib/esdoc.js:73:33)
    at HTMLElement.esdocParseEnter (/packages/esdoc/lib/esdoc.js:33:42)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -1:38.8.0 esdoc:parse-enter (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal 0.8.0 
atom-terminal-tab 0.2.2 
esdoc 0.0.7 
hacking-the-kernel 1.6.2 
hacking-the-kernel-ui 1.6.2 
```

**Comment by iocast** [comment]
@nahidakbar Could you reproduce the bug. I just upgraded to Atom 1.24.0 and this bug does not occur anymore.
