### ISSUE TITLE
Uncaught Error: esdoc expects valid JavaScript. Error parsing: Unexpected token (2:0)

### ISSUE THREAD

**Issue by pradyumnad** [iocast/atom-esdoc#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [esdoc](https://github.com/iocast/atom-esdoc) package 0.0.7

### Stack Trace

Uncaught Error: esdoc expects valid JavaScript. Error parsing: Unexpected token (2:0)

```
At C:\Users\408298.GENPT\.atom\packages\esdoc\lib\parser.js:172

Error: esdoc expects valid JavaScript. Error parsing: Unexpected token (2:0)
    at getAST (/packages/esdoc/lib/parser.js:172:11)
    at parse (/packages/esdoc/lib/parser.js:178:13)
    at comment (/packages/esdoc/lib/esdocer.js:9:14)
    at Object.generate (/packages/esdoc/lib/esdoc.js:54:9)
    at Object.parseEnter (/packages/esdoc/lib/esdoc.js:83:15)
    at HTMLElement.esdocParseEnter (/packages/esdoc/lib/esdoc.js:33:42)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.23.3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:33.8.0 esdoc:parse-enter (input.hidden-input)
     -0:32.4.0 core:undo (input.hidden-input)
     -0:24.9.0 core:move-right (input.hidden-input)
     -0:24.5.0 esdoc:parse-enter (input.hidden-input)
     -0:18.8.0 core:undo (input.hidden-input)
  2x -0:17.6.0 core:move-right (input.hidden-input)
     -0:16.8.0 editor:move-to-end-of-word (input.hidden-input)
     -0:16.1.0 esdoc:parse-tab (input.hidden-input)
     -0:14.9.0 core:undo (input.hidden-input)
  6x -0:14.1.0 editor:move-to-end-of-word (input.hidden-input)
  5x -0:12.6.0 editor:select-to-beginning-of-word (input.hidden-input)
  2x -0:11.3.0 core:backspace (input.hidden-input)
     -0:10.5.0 esdoc:parse-enter (input.hidden-input)
     -0:08.3.0 editor:consolidate-selections (input.hidden-input)
     -0:08.3.0 core:cancel (input.hidden-input)
     -0:06.8.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-formatter-jsbeautify 1.1.2 
esdoc 0.0.7 
javascript-snippets 1.2.1 
jsformat 0.9.3 
```

**Comment by iocast** [comment]
do you have an example file?

**Comment by iocast** [comment]
it seems that your file is not valid.
